{ repoRoot, inputs, pkgs, lib, system, extraPackages }:
# This setup depends on some env variables.
# They are provided by the shellHook in the ./shell.nix file.
let
  inherit (lib) mkForce;
  stateDir = "./.run";
  marloweRuntimeDir = "${stateDir}/runtime";

  cardano-node-ready = pkgs.writeShellApplication {
    name = "cardano-node-ready";
    text = ''
      [ -S "$CARDANO_NODE_SOCKET_PATH" ]
      cardano-cli ping -c 1 -u "$CARDANO_NODE_SOCKET_PATH" -m "$CARDANO_NODE_NETWORK_ID"
    '';
    runtimeInputs = [ inputs.cardano-node.packages.${pkgs.system}.cardano-cli ];
  };

  cardano-node-query = pkgs.writeShellApplication {
    name = "cardano-node-query";
    text = ''
      while true; do
        date -u --rfc-3339=seconds
        cardano-cli query tip
        echo
        sleep 10
      done
    '';
    runtimeInputs = [ inputs.cardano-node.packages.${pkgs.system}.cardano-cli ];
  };

  # Postgres process commands
  setup-postgres = let
    hbaConf = [
      {
        type = "local";
        database = "all";
        user = "all";
        address = "";
        method = "trust";
      }
      {
        type = "host";
        database = "all";
        user = "all";
        address = "127.0.0.1/32";
        method = "trust";
      }
      {
        type = "host";
        database = "all";
        user = "all";
        address = "::1/128";
        method = "trust";
      }
      {
        type = "local";
        database = "replication";
        user = "all";
        address = "";
        method = "trust";
      }
      {
        type = "host";
        database = "replication";
        user = "all";
        address = "127.0.0.1/32";
        method = "trust";
      }
      {
        type = "host";
        database = "replication";
        user = "all";
        address = "::1/128";
        method = "trust";
      }
    ];
    hbaConfString = ''
      # Generated by Nix
      ${''
        # TYPE	DATABASE	USER	ADDRESS	METHOD
      ''}
      ${lib.concatMapStrings (cnf:
        "  ${cnf.type}	${cnf.database}	${cnf.user}	${cnf.address}	${cnf.method}\n")
      hbaConf}
    '';
    hbaFile = pkgs.writeText "pg_hba.conf" hbaConfString;
    pgConfig = {
      listen_addresses = "127.0.0.1";
      port = 5432;
      hba_file = "${hbaFile}";
    };
    toStr = value:
      if true == value then
        "yes"
      else if false == value then
        "no"
      else if lib.isString value then
        "'${lib.replaceStrings [ "'" ] [ "''" ] value}'"
      else
        toString value;
    configFile = pkgs.writeText "postgresql.conf" (lib.concatStringsSep "\n"
      (lib.mapAttrsToList (n: v: "${n} = ${toStr v}") pgConfig));
  in pkgs.writeShellApplication {
    name = "setup-postgres";
    runtimeInputs = [ pkgs.postgresql pkgs.coreutils ];
    text = ''
      set -x
      function psql_with_args() {
        psql -v "ON_ERROR_STOP=1" "$@"
      }
      # Setup postgres ENVs
      export PGDATA="${stateDir}/postgres/pgdata"
      export PGPORT="''${PGPORT:-5432}"
      POSTGRES_RUN_INITIAL_SCRIPT="false"
      if [[ ! -d "$PGDATA" ]]; then
        initdb -D "$PGDATA"
        POSTGRES_RUN_INITIAL_SCRIPT="true"
        echo
        echo "PostgreSQL initdb process complete."
        echo
      fi
      # Setup config
      echo "Setting up postgresql.conf"
      cp ${configFile} "$PGDATA/postgresql.conf"
      sed -i "s/${
        toString pgConfig.port
      }/''${PGPORT}/" "$PGDATA/postgresql.conf"
      if [[ "$POSTGRES_RUN_INITIAL_SCRIPT" = "true" ]]; then
        echo
        echo "PostgreSQL is setting up the initial database."
        echo
        PGHOST="$(mktemp -d /tmp/pg-init-XXXXXX)"
        export PGHOST
        function remove_tmp_pg_init_sock_dir() {
          if [[ -d "$1" ]]; then
            rm -rf "$1"
          fi
        }
        trap 'remove_tmp_pg_init_sock_dir "$PGHOST"' EXIT
        pg_ctl -D "$PGDATA" -w start -o "-c unix_socket_directories=$PGHOST -c listen_addresses= -p $PGPORT"
        echo "CREATE DATABASE marlowe;" | psql_with_args -d postgres
        echo "CREATE USER marlowe;" | psql_with_args -d postgres
        echo "ALTER DATABASE marlowe OWNER TO marlowe;" | psql_with_args -d postgres
        pg_ctl -D "$PGDATA" -m fast -w stop
        remove_tmp_pg_init_sock_dir "$PGHOST"
      else
        echo
        echo "PostgreSQL database directory appears to contain a database; Skipping initialization"
        echo
      fi
      unset POSTGRES_RUN_INITIAL_SCRIPT
    '';
  };

  start-postgres = pkgs.writeShellApplication {
    name = "start-postgres";
    runtimeInputs = [ pkgs.postgresql pkgs.coreutils ];
    text = ''
      set -euox pipefail
      PGDATA="$(readlink -f "${stateDir}/postgres/pgdata")"
      export PGDATA
      postgres -D "$PGDATA" -k "$PGDATA"
    '';
  };
  setup-test-env = pkgs.writeShellApplication {
    name = "setup-test-env";
    runtimeInputs =
      [ inputs.cardano-node.packages.${pkgs.system}.cardano-cli pkgs.jq ];
    text = ''
      set -euo pipefail

      # Create test environment directory
      mkdir -p .run/ts-sdk

      # Copy utxo keys as faucet keys
      cp .run/testnet/utxo-keys/utxo1.vkey .run/ts-sdk/faucet.vkey
      cp .run/testnet/utxo-keys/utxo1.skey .run/ts-sdk/faucet.skey

      # Only create config file if MARLOWE_TESTING_KIT_CONFIG is not already set
      if [[ -z "''${MARLOWE_TESTING_KIT_CONFIG:-}" ]]; then
        MARLOWE_TESTING_KIT_CONFIG="$(pwd)/.run/ts-sdk/config.json"
        export MARLOWE_TESTING_KIT_CONFIG
      fi
      mkdir -p "$(dirname "$MARLOWE_TESTING_KIT_CONFIG")"
      if [[ ! -f "$MARLOWE_TESTING_KIT_CONFIG" ]]; then
        # Create config file using jq for proper JSON formatting
        jq -n \
          --arg skey "$(pwd)/.run/ts-sdk/faucet.skey" \
          --arg port "$MARLOWE_WEB_HTTP_PORT" \
          --arg version "$MARLOWE_RUNTIME_VERSION" \
          '{
            faucet: {
              type: "sKeyFile",
              value: $skey
            },
            runtime: {
              url: "http://localhost:\($port)",
              version: $version,
            },
            testnetMagic: 42
          }' > "$MARLOWE_TESTING_KIT_CONFIG"
      fi
    '';
  };

  setup-marlowe-runtime = let
    sqitch-conf = pkgs.writeText "sqitch.conf" ''
      [user]
        name = chainindexer
        email = example@example.com
    '';
  in pkgs.writeShellApplication {
    name = "setup-marlowe-runtime";
    runtimeInputs = [ pkgs.sqitchPg pkgs.postgresql pkgs.jq ];
    text = ''
      set -euo pipefail

      # Setup sqitch environment
      export SQITCH_USER_CONFIG=${sqitch-conf}
      export TZ=Etc/UTC

      # Deploy chain-sync schema
      echo "Deploying chain-sync schema..."
      cd ${inputs.marlowe-cardano.sqitch-plan-dirs.chain-sync}
      sqitch --quiet deploy --target "postgresql://marlowe@localhost:''${PGPORT:-5432}/marlowe"

      # Deploy runtime schema
      echo "Deploying runtime schema..."
      cd ${inputs.marlowe-cardano.sqitch-plan-dirs.runtime}
      sqitch --quiet deploy --target "postgresql://marlowe@localhost:''${PGPORT:-5432}/marlowe"

      # Create runtime store directory - is it really read-only at this point?
      # mkdir -p "${marloweRuntimeDir}/store"
    '';
  };

  kupo-health-check = pkgs.writeShellApplication {
    name = "kupo-health-check";
    runtimeInputs = [ pkgs.curl pkgs.jq ];
    text = ''
      response=$(curl -s -H "Accept: application/json" http://localhost:1442/health)
      connection_status=$(echo "$response" | jq -r '.connection_status')
      if [ "$connection_status" = "connected" ]; then
        exit 0
      fi
      # Print detailed status info on failure
      echo "Kupo health check failed. Full status:"
      echo "$response" | jq '.'
      exit 1
    '';
  };

  start-kupo = pkgs.writeShellApplication {
    name = "start-kupo";
    runtimeInputs = [ extraPackages.kupo ];
    text = ''
      kupo \
        --node-socket "$CARDANO_NODE_SOCKET_PATH" \
        --node-config ${stateDir}/testnet/configuration.yaml \
        --since origin \
        --defer-db-indexes \
        --match '*' \
        --workdir ${stateDir}/ts-sdk/kupo-db \
        --host 127.0.0.1 \
        --port 1442
    '';
  };

  ogmios-health-check = pkgs.writeShellApplication {
    name = "ogmios-health-check";
    runtimeInputs = [ pkgs.curl pkgs.jq ];
    text = ''
      response=$(curl -s http://localhost:1337/health)
      lastTipUpdate=$(echo "$response" | jq -r '.lastTipUpdate')
      # Check if lastTipUpdate exists and is not null
      if [ "$lastTipUpdate" != "null" ]; then
        # Try to parse the timestamp
        if date -d "$lastTipUpdate" > /dev/null 2>&1; then
          exit 0
        fi
      fi
      exit 1
    '';
  };

  start-ogmios = pkgs.writeShellApplication {
    name = "start-ogmios";
    runtimeInputs = [ extraPackages.ogmios ];
    text = ''
      ogmios \
        --node-socket "$CARDANO_NODE_SOCKET_PATH" \
        --node-config ${stateDir}/testnet/configuration.yaml \
        --host "127.0.0.1" \
        --port 1337
    '';
  };

  start-marlowe-web = pkgs.writeShellApplication {
    name = "start-marlowe-web";
    runtimeInputs =
      [ inputs.marlowe-cardano.packages.${system}.marlowe-web-server ];
    text = ''
      marlowe-web-server \
        --http-port "$MARLOWE_WEB_HTTP_PORT" \
        --marlowe-runtime-host 127.0.0.1 \
        --marlowe-runtime-port 3701 \
        --enable-open-api \
        --access-control-allow-origin-all
    '';
  };

  start-marlowe-runtime = pkgs.writeShellApplication {
    name = "start-marlowe-runtime";
    runtimeInputs = [
      inputs.marlowe-cardano.packages.${system}.marlowe-runtime
      inputs.marlowe-plutus.packages.${system}.marlowe-minting-validator
      inputs.cardano-node.packages.${system}.cardano-cli
      pkgs.z3
      pkgs.postgresql
    ];
    text = ''
      BYRON_GENESIS_JSON=${stateDir}/testnet/genesis/byron/genesis.json
      marlowe-runtime \
        --socket-path "$CARDANO_NODE_SOCKET_PATH" \
        --testnet-magic "$CARDANO_NODE_NETWORK_ID" \
        --database-uri "postgresql://marlowe@localhost:''${PGPORT:-5432}/marlowe" \
        --shelley-genesis-config-file ${stateDir}/testnet/genesis/shelley/genesis.json \
        --genesis-config-file "$BYRON_GENESIS_JSON" \
        --genesis-config-file-hash "$(cardano-cli byron genesis print-genesis-hash --genesis-json "$BYRON_GENESIS_JSON")" \
        --store-dir ${marloweRuntimeDir}/store \
        --host 0.0.0.0 \
        --port 3700 \
        --port-traced 3701 \
        --http-port 3702 \
        --minting-policy-cmd marlowe-minting-validator \
        --min-contract-age 87400s \
        --max-store-size 8589934592
    '';
  };
  clear-state = pkgs.writeShellApplication {
    name = "clear-state";
    text = ''
      set -exuo pipefail
      rm -fR ${stateDir}
      target="$(realpath --no-symlinks ${stateDir}/testnet)"
      (cd testnet; scripts/babbage/mkfiles.sh "$target")
    '';
  };
in (pkgs.formats.yaml { }).generate "process-compose.yaml" {
  version = "0.5";
  processes = {
    clear-state = { command = "${clear-state}/bin/clear-state"; };
    cardano-node-1 = {
      namespace = "cardano-node";
      log_location = "${stateDir}/testnet/cardano-node-1.log";
      command = "${stateDir}/testnet/node-spo1.sh";
      ready_log_line = "TraceNodeIsLeader";
      depends_on.clear-state.condition = "process_completed_successfully";
    };

    cardano-node-2 = {
      namespace = "cardano-node";
      log_location = "${stateDir}/testnet/cardano-node-2.log";
      command = "${stateDir}/testnet/node-spo2.sh";
      ready_log_line = "TraceNodeIsLeader";
      depends_on.clear-state.condition = "process_completed_successfully";
    };

    cardano-node-3 = {
      namespace = "cardano-node";
      log_location = "${stateDir}/testnet/cardano-node-3.log";
      command = "${stateDir}/testnet/node-spo3.sh";
      ready_log_line = "TraceNodeIsLeader";
      depends_on.clear-state.condition = "process_completed_successfully";
    };

    cardano-node-query = {
      command = "${cardano-node-query}/bin/cardano-node-query";
      depends_on.cardano-node-1.condition = "process_log_ready";
      # environment = [
      #   "CARDANO_NODE_NETWORK_ID=42"
      #   "CARDANO_NODE_SOCKET_PATH=${stateDir}/testnet/node-spo1/node.sock"
      # ];
      log_location = "${stateDir}/testnet/cardano-node-query.log";
      namespace = "cardano-node";
    };

    postgres-init = {
      command = "${setup-postgres}/bin/setup-postgres";
      depends_on."clear-state".condition = "process_completed_successfully";
      log_location = "${stateDir}/postgres/postgres-init.log";
      namespace = "postgresql";
    };

    postgres = {
      availability = {
        restart = "on_failure";
        max_restarts = 5;
      };
      command = "${start-postgres}/bin/start-postgres";
      depends_on."postgres-init".condition = "process_completed_successfully";
      log_location = "${stateDir}/postgres/postgres.log";
      namespace = "postgresql";
      readiness_probe = {
        exec.command = ''
          ${pkgs.postgresql}/bin/pg_isready -h 127.0.0.1 -p "''${PGPORT:-5432}" -d template1'';
        initial_delay_seconds = 2;
        period_seconds = 10;
        timeout_seconds = 4;
        success_threshold = 1;
        failure_threshold = 5;
      };
      shutdown.signal = 2;
    };

    marlowe-runtime-setup = {
      command = "${setup-marlowe-runtime}/bin/setup-marlowe-runtime";
      depends_on = { "postgres".condition = "process_healthy"; };
      log_location = "${marloweRuntimeDir}/setup.log";
      namespace = "marlowe-runtime";
    };

    marlowe-runtime = {
      depends_on = {
        "cardano-node-1".condition = "process_healthy";
        "postgres".condition = "process_healthy";
        "marlowe-runtime-setup".condition = "process_completed_successfully";
      };
      environment = [
        "CARDANO_NODE_NETWORK_ID=42"
        "CARDANO_NODE_SOCKET_PATH=${stateDir}/testnet/node-spo1/node.sock"
      ];
      command = "${start-marlowe-runtime}/bin/start-marlowe-runtime";
      log_location = "${marloweRuntimeDir}/marlowe-runtime.log";
      namespace = "marlowe-runtime";
      readiness_probe = {
        exec.command = "curl -f http://localhost:3702/ready";
        period_seconds = 10;
        timeout_seconds = 5;
        failure_threshold = 3;
      };
    };

    setup-test-env = {
      command = "${setup-test-env}/bin/setup-test-env";
      depends_on."marlowe-web".condition = "process_healthy";
      log_location = "${stateDir}/ts-sdk/setup.log";
      namespace = "ts-sdk";
    };

    kupo = {
      depends_on = { "cardano-node-1".condition = "process_healthy"; };
      command = "${start-kupo}/bin/start-kupo";
      log_location = "${stateDir}/kupo/kupo.log";
      namespace = "cardano-node";
      readiness_probe = {
        exec.command = "${kupo-health-check}/bin/kupo-health-check";
        period_seconds = 10;
        timeout_seconds = 5;
        failure_threshold = 10;
      };
    };

    ogmios = {
      depends_on = { "cardano-node-1".condition = "process_healthy"; };
      command = "${start-ogmios}/bin/start-ogmios";
      log_location = "${stateDir}/ogmios/ogmios.log";
      namespace = "cardano-node";
      readiness_probe = {
        exec.command = "${ogmios-health-check}/bin/ogmios-health-check";
        period_seconds = 10;
        timeout_seconds = 5;
        failure_threshold = 3;
      };
    };

    marlowe-web = {
      depends_on = { "marlowe-runtime".condition = "process_healthy"; };
      command = "${start-marlowe-web}/bin/start-marlowe-web";
      log_location = "${marloweRuntimeDir}/marlowe-web.log";
      namespace = "marlowe-runtime";
      readiness_probe = {
        exec.command =
          "curl -f http://localhost:$MARLOWE_WEB_HTTP_PORT/healthcheck";
        period_seconds = 10;
        timeout_seconds = 5;
        failure_threshold = 3;
      };
    };
  };
}
