{ repoRoot, inputs, pkgs, lib, system, extraPackages }:
lib.iogx.mkShell {
  name = "ts-sdk";

  packages = [
    pkgs.pkg-config
    pkgs.deno
    pkgs.scriv
    pkgs.nodePackages.nodejs
    pkgs.nodePackages.prettier
    pkgs.nodePackages.prettier-plugin-toml
    pkgs.postgresql
    pkgs.process-compose

    inputs.marlowe-spec.packages.marlowe-spec
    inputs.cardano-node.packages.cardano-node
    inputs.cardano-node.packages.cardano-cli

    extraPackages.cardano-address
    extraPackages.kupo
    extraPackages.ogmios
  ];

  scripts.build-changelog = {
    description = "Makes a changelog release from the changelog.d fragments";
    group = "ts-sdk";
    exec = ''
      VERSION=$(jq ".version" package.json)
      echo "Writting changelog for version $VERSION"
      scriv collect --version "$VERSION"
    '';
  };

  scripts.test-spec = let
    marlowe-spec-program = pkgs.writeShellApplication {
      name = "marlowe-spec-program";
      runtimeInputs = [ pkgs.nodePackages.nodejs ];
      text = ''
        node packages/language/specification-client/dist/esm/main.js
      '';
    };
  in {
    group = "ts-sdk";
    description = "Runs the Marlowe Spec test suite";
    exec = "marlowe-spec -c ${lib.getExe marlowe-spec-program}";
  };
  scripts.deploy-local-testnet = {
    description = "Start and run an ephemeral local testnet";
    group = "general";
    exec = ''
      set -e
      set -u
      set -o pipefail

      ROOT="$(realpath --no-symlinks "''${1-testnet/example}")"

      cd $(git rev-parse --show-toplevel)/testnet
      [ -f "$ROOT/configuration.yaml" ] || scripts/babbage/mkfiles.sh "$ROOT"
      cd "$ROOT"
      ./run/all.sh
    '';
  };
  scripts.purge-local-testnet = {
    description = "Cleanup the local testnet directory";
    group = "general";
    exec = ''
      set -e
      set -u
      set -o pipefail

      rm -rf "''${1-testnet/example}"
    '';
  };

  env = {
    PC_CONFIG_FILES = (import ./process-compose-yaml.nix {
      inherit repoRoot inputs pkgs lib system extraPackages;
    });
    PC_PORT_NUM = "8100";
  };

  shellHook = ''
    # Only set defaults if not already defined
    export CARDANO_NODE_SOCKET_PATH="''${CARDANO_NODE_SOCKET_PATH:-$(git rev-parse --show-toplevel)/.run/testnet/node-spo1/node.sock}"
    export CARDANO_NODE_NETWORK_ID="''${CARDANO_NODE_NETWORK_ID:-42}"
    export MARLOWE_TESTING_KIT_CONFIG="''${MARLOWE_TESTING_KIT_CONFIG:-$(git rev-parse --show-toplevel)/.run/ts-sdk/config.json}"
    # We override the default port here actually ourselves by doing so we enforce it during process-compose setup.
    export MARLOWE_WEB_HTTP_PORT="''${MARLOWE_WEB_HTTP_PORT:-19100}"
    # Expected version which we should develop against
    export MARLOWE_RUNTIME_VERSION="''${MARLOWE_RUNTIME_VERSION:-1.0.1}"
    export PGPORT="''${PGPORT:-15432}"
  '';

  # NOTE: jsdelivr-npm-importmap.js is generated by 'npm run build' and causes
  # formatting issues in CI, hence why we exclude it from the formatting checks.
  #   editorconfig-checker.enable = true;
  #   editorconfig-checker.excludes = [ "jsdelivr-npm-importmap\\.js" ];

  #   prettier.enable = true;
  #   # prettier.printWidth = 120;
  #   # prettier.extraOptions = "--plugin ${pkgs.nodePackages.prettier-plugin-toml}/lib/node_modules/prettier-plugin-toml/lib/api.js --write";
  #   # prettier.excludes = [ "jsdelivr-npm-importmap\\.js" ];
  #   # prettier.files = "\\.(css|html|js|json|jsx|scss|ts|yaml|toml)$";
  # };

  preCommit = {
    cabal-fmt.enable = true;
    cabal-fmt.extraOptions = "--no-tabular";
    fourmolu.enable = true;
    hlint.enable = false;
    shellcheck.enable = false;
    prettier = {
      enable = true;
      excludes = [ "jsdelivr-npm-importmap\\.js" ];
      extraOptions =
        "--single-quote --plugin ${pkgs.nodePackages.prettier-plugin-toml}/lib/node_modules/prettier-plugin-toml/lib/index.js --write";
      files = "\\.(css|html|js|json|jsx|scss|ts|yaml|toml)$";
    };
    # Eslint has a lot of problems in the current setup. Probably we should point it to the config directly - investigate the debug log further.
    # eslint = {
    #   enable = true;
    #   entry = "npx eslint --fix";
    #   extraOptions = "--ext .js,.ts,.jsx,.tsx --max-warnings 0 --debug";
    #   pass_filenames = true;
    # };
    nixfmt-classic.enable = true;
  };
}

